spring.application.name=Job-Portal
spring.data.mongodb.uri=mongodb+srv://Imran:Imran123@mycluster.menyj.mongodb.net/jobportal?retryWrites=true&w=majority&appName=MyCluster
spring.data.mongodb.auto-index-creation=true




#Email Properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ik6518793@gmail.com
spring.mail.password=mbkwwgrjhyvgfndy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=UGV0ZXJAIzEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MAo=
jwt.expiration=36000000

USER_FOUND=User has registered already.
USER_NOT_FOUND=User is not registered.
INVALID_CREDENTIALS=Invalid Credentials.
OTP_NOT_FOUND=OTP is Expired.
OTP_INCORRECT=OTP is incorrect.

JOB_NOT_FOUND=Job not found.
JOB_APPLIED_ALREADY=Job applied already.